metal lowbit kernels: executorch ops
pytorch/ao pull request #1322
Opened 2024-11-22 01:02 UTC by manuelcandales

Summary:
Refactors kernels/mps/src/OperationUntils.h, moving MetalShaderLibrary into its own header.
Integrates MPS delegate functions into lowbit.h
Registers out variants for the ATen ops
Registers ET ops

Differential Revision: D65957345

2024-12-10 21:00 UTC, kimishpatel requested changes
Left a few comments

2024-12-11 01:05 UTC, manuelcandales commented on torchao/experimental/quant_api.py
> -
discussed offline

2024-12-11 01:16 UTC, manuelcandales commented on torchao/experimental/ops/mps/CMakeLists.txt
> +    include_directories(${CMAKE_INSTALL_PREFIX}/../third-party/flatbuffers/include)
Needed to build llama runner with the mps custom ops

2024-12-11 01:16 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/lowbit.h
> +#else
discussed offline

2024-12-12 03:36 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/MetalShaderLibrary.h
> +    return get_compute_pipeline_state(load_func(fname));
done!

2024-12-12 03:36 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/MetalShaderLibrary.h
> +#ifndef USE_EXECUTORCH // TODO(mcandales): Unify with ET error handling
done!

2024-12-12 03:36 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/MetalShaderLibrary.h
> +#ifndef USE_EXECUTORCH // TODO(mcandales): Unify with ET error handling
done!

2024-12-12 03:36 UTC, manuelcandales commented on torchao/experimental/ops/mps/CMakeLists.txt
> +        EXPORT _targets
deleted

2024-12-12 03:37 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/MetalShaderLibrary.h
> +static id<MTLDevice> MTL_DEVICE = MPSDevice::getInstance()->device();
refactored

2024-12-12 04:11 UTC, kimishpatel commented
Did you forget to push commit? I see only one commit

2024-12-12 17:12 UTC, manuelcandales commented on torchao/experimental/kernels/mps/src/lowbit.h
>    MPSStream* mpsStream = getCurrentMPSStream();
> So for PT integration we are using a separate implementation of this? And for executorch we use one from delegate?

For PT we are using the getCurrentMPSStream implementation from the ATen MPS code, and for ET we are using the getCurrentMPSStream implementation from the ET MPS delegate code.

> Also what is the interaction with device and the stream? It seems that you are creating your own device when compiling for PyTorch, but then use getCurrentMPSStream from aten?

I am not creating a device in any of those cases (PT or ET). In those cases I basically just retrieve the device via MPSDevice::getInstance()->device(). It is the same in that respect PT vs ET.

2024-12-12 21:30 UTC, kimishpatel approved these changes

2024-12-13 01:49 UTC, merged