[Feat]: Add support for kleidiai quantization schemes
pytorch/ao pull request #1447
Opened 2024-12-19 10:44 UTC by ng-05

Description:
1. Allow Int4WeightOnlyQuantizer to work with channelwise and groupwise symmetric quantization schemes
2. KleidiAI supports channelwise and 32 groupwise quantized matmul kernels

2024-12-20 21:40 UTC, jerryzh168 commented on torchao/quantization/GPTQ.py
we plan to deprecate the APIs in this file actually, you should be extending APIs from this file instead: https://github.com/pytorch/ao/blob/main/torchao/quantization/quant_api.py

2024-12-20 22:05 UTC, ng-05 commented on torchao/quantization/GPTQ.py
Thanks, Noted!

2025-01-08 12:14 UTC, ng-05 commented
Hello @jerryzh168 ,
We want to support two diff type of int4 schemes. 
1. symmetric_groupwise -> groupsize [ 32, 64, 128 etc ]
2. symmetric_channelwise -> groupsize is equal to channelsize of the matmul weights


How should we take this input from user regarding quantization schemes. Groupsize parameter can not server the purpose as channelsize will change for diff matmuls in a model?

Currently I am using "scheme" parameter to differentiate between the two.
[aarch64_cpu_channelwise.json](https://github.com/ARM-software/Tool-Solutions/blob/main/ML-Frameworks/pytorch-aarch64/examples/gen_ai_utils/quant_configs/aarch64_cpu_channelwise.json)
[aarch64_cpu_groupwise.json](https://github.com/ARM-software/Tool-Solutions/blob/main/ML-Frameworks/pytorch-aarch64/examples/gen_ai_utils/quant_configs/aarch64_cpu_groupwise.json)

2025-01-08 17:44 UTC, jerryzh168 commented
> How should we take this input from user regarding quantization schemes. Groupsize parameter can not server the purpose as channelsize will change for diff matmuls in a model?

yeah, you can use https://github.com/pytorch/ao/blob/main/torchao/quantization/granularity.py (PerGroup and PerAxis(axis=0)), examples: https://github.com/pytorch/ao/blob/070345d9676f3dd6cdd325e987764fc3c71ccaf5/torchao/quantization/quant_api.py#L1069, https://github.com/pytorch/ao/blob/070345d9676f3dd6cdd325e987764fc3c71ccaf5/tutorials/calibration_flow/static_quant.py#L168

2025-01-09 02:00 UTC, ng-05 commented
> > How should we take this input from user regarding quantization schemes. Groupsize parameter can not server the purpose as channelsize will change for diff matmuls in a model?
> 
> yeah, you can use https://github.com/pytorch/ao/blob/main/torchao/quantization/granularity.py: PerGroup and PerAxis(axis=0) (assuming channel dimension is 0), examples:
> 
> https://github.com/pytorch/ao/blob/070345d9676f3dd6cdd325e987764fc3c71ccaf5/torchao/quantization/quant_api.py#L1069
> 
> ,
> https://github.com/pytorch/ao/blob/070345d9676f3dd6cdd325e987764fc3c71ccaf5/tutorials/calibration_flow/static_quant.py#L168

Thanks for the inputs @jerryzh168.

I have initial change ready which extends [int4_weight_only](https://github.com/pytorch/ao/blob/main/torchao/quantization/quant_api.py#L687) quantizer. 

The 4 bit KleidiAI kernels quantizes the weight in torchao and input to 8 bit within the kernel itself instead of quantizing the input in the torchao the way [int8_dynamic_activation_int4_weight](https://github.com/pytorch/ao/blob/main/torchao/quantization/quant_api.py#L631) does. 
For this reason I am extending the int4_weight_only api. I am slightly confused if the intention of this api is to convey NO input quantisation to user?

Currently neither int4_weight_only nor int8_dynamic_activation_int4_weight fully aligns with the way kelidiai 4 bit kernels are working. 

I feel int4_weight_only is closest to what we want to do, what are your thoughts on this?

2025-01-09 02:33 UTC, jerryzh168 commented
> I feel int4_weight_only is closest to what we want to do, what are your thoughts on this?

yeah int4_weight_only means no input quantization, I think it aligns better with `int8_dynamic_activation_int4_weight`, you can use a different layout and customize the logic for input quantization.

we also have https://github.com/pytorch/ao/blob/47383779c0975fd7ec213bc7b07c34ca5a1e5abb/torchao/experimental/quant_api.py#L485 that is the same as your use case. there is some ongoing refactors/updates there as well right now

2025-01-11 01:43 UTC, ng-05 commented
Hello @jerryzh168 , I am planning to migrate ```int8_dynamic_activation_intx_weight``` api  to ```int8_dynamic_activation_intx_weight_v2```. 
For now I have kept the API separate for review and testing. 

Can you please review this change, specially the change the in ```_get_linear_subclass_inserter``` which allow bias propagation. The bias needed by ```torch.ops.aten._dyn_quant_pack_4bit_weight```.

2025-01-11 02:31 UTC, jerryzh168 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    bias: Optional[torch.Tensor] = None
layout is more of a "type" actually, why is bias Tensor passed here?

2025-01-11 02:34 UTC, jerryzh168 commented on torchao/quantization/quant_api.py
> +        args = [lin.weight]
nit: I feel putting optional args in kwargs might be better

2025-01-11 02:36 UTC, jerryzh168 approved these changes
looks good to me overall, can you add some tests?

2025-01-11 02:37 UTC, jerryzh168 commented
> I am also not sure if int8_dynamic_activation_intx_weight* quantizer can be accessed by torchchat currently? Do you have an example how torchchat can pass args like granularity, mapping_type from torchchat cli to torchao ?

I don't think we need to expose these fine grained args to torchchat cli, we just need these high level args like: https://github.com/pytorch/torchchat/blob/main/torchchat/quant_config/mobile.json

we are also working on migrating torchchat to use torchao quant api btw

2025-01-11 03:57 UTC, kimishpatel commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    if TORCH_VERSION_AT_LEAST_2_6 and layout.target == Target.ATEN:
If torch version is not 2.6 but layout.target == aten, then what happens? Should you just assert that it is not supported?

2025-01-11 04:06 UTC, kimishpatel commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +        print("TODO bias == None")
assert bias == None, <msg>

2025-01-11 04:06 UTC, kimishpatel commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    if input_tensor.dim() == 2:
Do you have this requirement?

2025-01-11 04:15 UTC, metascroy commented on torchao/experimental/quant_api.py
> +def int8_dynamic_activation_intx_weight_v2(
I'm currently refactoring int8_dynamic_activation_intx_weight quantizer to use layout instead of target for the packing format: https://github.com/pytorch/ao/pull/1553.  I think this should provide more flexibility longterm.

2025-01-11 04:18 UTC, metascroy commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
>              return self.packed_weight, self.scale, self.zero_point
IIUC when using Target.ATEN, self.packed_weight is not the int_data, so I'm not sure get_plain is correct here?

2025-01-11 04:22 UTC, kimishpatel commented on torchao/experimental/quant_api.py
> +def int8_dynamic_activation_intx_weight_v2(
is there a significant diffrence between this and int8_dynamic_activation_intx_weight?

2025-01-11 04:27 UTC, kimishpatel requested changes
I understand that this quant API now connects kernels we landed in aten with quant API. If the kernels you guys landed in aten are actually new ops, unlike int4pack_mm and friends, then why did we land them there in the first place. In order to reach those kernels you need ao dep anyway? (@digantdesai I know you tagged me on that PR but i never really deep dived into that so maybe you have context here)

Besides taht i have a couple of questions.
- In the current form it is only making aten op you guys added available via tensor subclass api, so what happens to say torch.compile (maybe this works?) or AOTI usecase?
- I would also like to see if we can leverage this op in executorch, for which integration into AO would have been a better choice compared to this being aten op
- If kleidi's op performs better than whats in this repo (and note that @digantdesai has actually integrated some of the kleidi ops that I guess you guys are aware of), then can we just use that op directly or have a path to kleidi's impl for the cpu ops that exist under experimental/ops?

2025-01-11 04:28 UTC, kimishpatel commented
> > Hello @jerryzh168 , I am planning to migrate `int8_dynamic_activation_intx_weight` api to `int8_dynamic_activation_intx_weight_v2`. For now I have kept the API separate for review and testing.
> > Can you please review this change, specially the change the in `_get_linear_subclass_inserter` which allow bias propagation. The bias needed by `torch.ops.aten._dyn_quant_pack_4bit_weight`.
> > I am also not sure if int8_dynamic_activation_intx_weight* quantizer can be accessed by torchchat currently? Do you have an example how torchchat can pass args like granularity, mapping_type from torchchat cli to torchao ?
> 
> torchchat does not currently use int8_dynamic_activation_intx_weight, but instead a submodule swap API here: [`main`/torchao/experimental/quant_api.py#L438](https://github.com/pytorch/ao/blob/main/torchao/experimental/quant_api.py#L438)
> 
> We will be switching torchchat to use int8_dynamic_activation_intx_weight instead, but I first need to land some changes for perf/clarity: #1553

Any specific reason why use subclass API instead of module swap?

2025-01-13 12:30 UTC, ng-05 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    bias: Optional[torch.Tensor] = None
I want to access the bias to be packed with my weights and scales. I can not find any other existing way to pass bias to ```from_plain()``` api via https://github.com/pytorch/ao/blob/ad61822f4101625092dd8d2d59d4be6438341791/torchao/dtypes/affine_quantized_tensor.py#L281

How do you think I should access bias in the packing function here. https://github.com/pytorch/ao/blob/ad61822f4101625092dd8d2d59d4be6438341791/torchao/experimental/_linear_8bit_act_xbit_weight_layout.py#L77

2025-01-13 12:31 UTC, ng-05 commented on torchao/quantization/quant_api.py
> +        args = [lin.weight]
If you put bias in optional kwargs, all the functions similar to "apply()" will start complaining and need changes

2025-01-13 12:31 UTC, ng-05 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    if TORCH_VERSION_AT_LEAST_2_6 and layout.target == Target.ATEN:
Good Catch. Should be assert

2025-01-13 12:32 UTC, ng-05 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +        print("TODO bias == None")
Good Catch, thanks. I Missed this

2025-01-13 12:32 UTC, ng-05 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    if input_tensor.dim() == 2:
Yes we only support 2d Input tensor in ```torch.ops.aten._dyn_quant_matmul_4bit```

2025-01-13 12:41 UTC, ng-05 commented
> I understand that this quant API now connects kernels we landed in aten with quant API. If the kernels you guys landed in aten are actually new ops, unlike int4pack_mm and friends, then why did we land them there in the first place. In order to reach those kernels you need ao dep anyway? (@digantdesai I know you tagged me on that PR but i never really deep dived into that so maybe you have context here)
> 
> Besides taht i have a couple of questions.
> 
> * In the current form it is only making aten op you guys added available via tensor subclass api, so what happens to say torch.compile (maybe this works?) or AOTI usecase?
> * I would also like to see if we can leverage this op in executorch, for which integration into AO would have been a better choice compared to this being aten op
> * If kleidi's op performs better than whats in this repo (and note that @digantdesai has actually integrated some of the kleidi ops that I guess you guys are aware of), then can we just use that op directly or have a path to kleidi's impl for the cpu ops that exist under experimental/ops?

I am unaware of executorch status and what performance you get with klediai kernels over there. I tested this change with torch.compile() and it seems to be working fine.

2025-01-13 18:56 UTC, metascroy commented
> > > Hello @jerryzh168 , I am planning to migrate `int8_dynamic_activation_intx_weight` api to `int8_dynamic_activation_intx_weight_v2`. For now I have kept the API separate for review and testing.
> > > Can you please review this change, specially the change the in `_get_linear_subclass_inserter` which allow bias propagation. The bias needed by `torch.ops.aten._dyn_quant_pack_4bit_weight`.
> > > I am also not sure if int8_dynamic_activation_intx_weight* quantizer can be accessed by torchchat currently? Do you have an example how torchchat can pass args like granularity, mapping_type from torchchat cli to torchao ?
> > 
> > 
> > torchchat does not currently use int8_dynamic_activation_intx_weight, but instead a submodule swap API here: [`main`/torchao/experimental/quant_api.py#L438](https://github.com/pytorch/ao/blob/main/torchao/experimental/quant_api.py#L438)
> > We will be switching torchchat to use int8_dynamic_activation_intx_weight instead, but I first need to land some changes for perf/clarity: #1553
> 
> Any specific reason why use subclass API instead of module swap?

My understanding from @jerryzh168 is that long-term, torchao plans to support pt2e and subclass/quantize_ based quantization long-term.  I believe torchchat is working on (and has already partially completed) moving module-swap based quantization over to use quantize_ (cc @Jack-Khuu to keep me honest there).

2025-01-13 19:08 UTC, metascroy commented on torchao/experimental/quant_api.py
> +def int8_dynamic_activation_intx_weight_v2(
In the new flow, fallback is achieved by passing layout=PlainLayout() to int8_dynamic_activation_intx_weight.  Native is achieved by passing PackedLinearInt8DynamicActivationIntxWeightLayout() as layout.

You would need to add a new layout for your op, e.g., PackedLinearInt8DynamicActivationIntxWeightKleidiAILayout or something (for what you call target=ATEN in this PR).

If you integrate the KleidiAI kernels with torchao as @digantdesai mentioned, you should be able to reuse PackedLinearInt8DynamicActivationIntxWeightLayout and KleidiAI can be dispatched to inside the torchao ops when appropriate.  If absolutely needed, we can add a target to the constructor for PackedLinearInt8DynamicActivationIntxWeightLayout. 

> I do not want to build and load torchao ops lib if I can directly leverage aten op

As an FYI, these ops are now built and loaded when torchao is pip installed locally.  Albeit they are still not present in the nightlies.

2025-01-14 04:03 UTC, kimishpatel commented
> > I understand that this quant API now connects kernels we landed in aten with quant API. If the kernels you guys landed in aten are actually new ops, unlike int4pack_mm and friends, then why did we land them there in the first place. In order to reach those kernels you need ao dep anyway? (@digantdesai I know you tagged me on that PR but i never really deep dived into that so maybe you have context here)
> > Besides taht i have a couple of questions.
> > 
> > * In the current form it is only making aten op you guys added available via tensor subclass api, so what happens to say torch.compile (maybe this works?) or AOTI usecase?
> > * I would also like to see if we can leverage this op in executorch, for which integration into AO would have been a better choice compared to this being aten op
> > * If kleidi's op performs better than whats in this repo (and note that @digantdesai has actually integrated some of the kleidi ops that I guess you guys are aware of), then can we just use that op directly or have a path to kleidi's impl for the cpu ops that exist under experimental/ops?
> 
> I am unaware of executorch status and what performance you get with klediai kernels over there. I tested this change with torch.compile() and it seems to be working fine.

are you planning to move dynamic quantized ops in aten to torchao?

2025-01-14 04:12 UTC, jerryzh168 commented
> 
> Any specific reason why use subclass API instead of module swap?

you mean quantize_ API right? it is the officially supported API for inference path of torchao

2025-01-14 04:16 UTC, jerryzh168 commented
agree with @kimishpatel that we want these ops in ao instead of aten, but I talked to @digantdesai last time he explains here: https://github.com/pytorch/pytorch/issues/143289#issuecomment-2555819375

2025-01-14 04:17 UTC, jerryzh168 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    bias: Optional[torch.Tensor] = None
If it does not fit into `AQT`, I think it's fine to create a new tensor subclass

2025-01-14 04:18 UTC, jerryzh168 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
> +    bias: Optional[torch.Tensor] = None
layout is following the design of https://pytorch.org/docs/stable/tensor_attributes.html#torch.layout

2025-01-14 16:30 UTC, digantdesai commented
> are you planning to move dynamic quantized ops in aten to torchao?

@kimishpatel - long term yes, but in the short term we might support `aten` backend here. Two main blockers, 
(1) as I said earlier on the ATen op PR https://github.com/pytorch/pytorch/issues/143289#issuecomment-2555819375 about Kleidi in two places, and 
(2) solidify out the torchAO apis (bias packing, layout clean up from Scott R., module swap to dispatch), move out of experimental, and integrate Kleidi ops with low-bit kernels.

I think if we unblock leveraging ATen op for now from here for eager/compile, we can solve (1) and (2) without blocking actual LLM use cases, this was a time sensitive demo request from Arm side for PT2.6.

2025-01-15 11:29 UTC, ng-05 commented on torchao/experimental/_linear_8bit_act_xbit_weight_layout.py
>              return self.packed_weight, self.scale, self.zero_point
What is the idea behind get_plain() api? Does it return the unpacked original tensors of the Linear layer? If yes, why is it returning the packed weights in original implementation?
@metascroy what do you mean by ```int_data```  in your first comment?

2025-01-15 12:35 UTC, ng-05 commented on torchao/experimental/quant_api.py
> +def int8_dynamic_activation_intx_weight_v2(
I will add ```has_bias``` and ```target``` to ```PackedLinearInt8DynamicActivationIntxWeightLayout()```

2025-01-15 15:01 UTC, kimishpatel commented
> > are you planning to move dynamic quantized ops in aten to torchao?
> 
> @kimishpatel - long term yes, but in the short term we might support `aten` backend here. Two main blockers, (1) as I said earlier on the ATen op PR [pytorch/pytorch#143289 (comment)](https://github.com/pytorch/pytorch/issues/143289#issuecomment-2555819375) about Kleidi in two places, and (2) solidify out the torchAO apis (bias packing, layout clean up from Scott R., module swap to dispatch), move out of experimental, and integrate Kleidi ops with low-bit kernels.
> 
> I think if we unblock leveraging ATen op for now from here for eager/compile, we can solve (1) and (2) without blocking actual LLM use cases, this was a time sensitive demo request from Arm side for PT2.6.

Thanks for the context Digant. Lets make sure we make progress on the long term front

2025-01-15 18:44 UTC, ng-05 commented
I have done the changes as per the review comments and latest refactoring ```(PackedLinearInt8DynamicActivationIntxWeightLayout)```
Can I please get a review @metascroy @digantdesai

2025-01-17 03:55 UTC, jerryzh168 commented on torchao/dtypes/affine_quantized_tensor.py
> +        bias: Optional[torch.Tensor] = None
probably better to inherit from AQT and customize this for now I feel, see https://github.com/pytorch/ao/blob/cf453360dd3e09394657172f8e8d8da23cfbf043/torchao/dtypes/uintx/marlin_qqq_tensor.py#L31 for an example

2025-01-17 04:00 UTC, jerryzh168 commented on torchao/quantization/quant_api.py
> +        args = [lin.weight]
why? I thought we still only put it when propagate_bias is True

2025-01-17 04:01 UTC, kimishpatel commented
I have expressed my high level concerns which has been discussed. So I am gonna leave rest of the review to @metascroy and @digantdesai

2025-01-17 13:15 UTC, ng-05 commented on torchao/dtypes/affine_quantized_tensor.py
> +        bias: Optional[torch.Tensor] = None
Thanks for your input @jerryzh168 . I have made the changes as per your suggestion.

2025-01-17 13:18 UTC, ng-05 commented on torchao/quantization/quant_api.py
> +        args = [lin.weight]
sorry I thought you wanted lin.weight to be passed as part of kwargs. lin.bias can be passed as part of kwargs. This change is done

2025-01-17 19:26 UTC, metascroy commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
>      has_weight_zeros: Optional[bool]
The packed weights from Kleidi have bias packed with them, right?  If so, let's add has_bias: Optional[bool] here to layout.

2025-01-17 19:33 UTC, metascroy commented on torchao/experimental/quant_api.py
> +                has_weight_zeros != True or \
It looks like the KleidiAI op does not take the zero points during packing (scale-only quantization)?  So shouldn't has_weight_zeros be false?

2025-01-17 19:36 UTC, metascroy commented on torchao/experimental/quant_api.py
> +    target: str = "native",
I think it would be better to pass this in layout's constructor because it isn't related to the quantization intent, but packing format/kernel selection e.g., layout= PackedLinearInt8DynamicActivationIntxWeightLayout(target="native")

2025-01-17 19:41 UTC, metascroy commented on torchao/experimental/quant_api.py
> +    elif not isinstance(layout, PlainLayout):
Guard this try/except on `if isisntance(layout, PackedLinearInt8DynamicActivationIntxWeightLayout)` instead.  In case other layout is added in future, guarding on not PlainLayout is too broad.

2025-01-17 19:43 UTC, metascroy commented on torchao/experimental/quant_api.py
> +                        scale_dtype = torch.bfloat16 # KleidiAI kernel requires bfloat16 scale_dtype
Only bfloat16 on PerGroup, but not on PerRow?

2025-01-17 19:50 UTC, metascroy commented on torchao/experimental/quant_api.py
> +    if target == "aten":
Can this be something like:

```
if isinstance(layout, PackedLinearInt8DynamicActivationIntxWeightLayout):
    if taget == "aten":
        # Do KleidiAI checks
    
    if target == "native":
        # Do try/except import logic
```

2025-01-17 19:58 UTC, metascroy commented
Overall I think it's close.  Can you be sure to run `torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py` to make sure the tests pass.  It is not currently enabled in CI.

You should also add some test cases for your new target to that file to check accuracy/exportability.

2025-01-20 02:32 UTC, metascroy commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +class PackedLinearInt8DynamicActivationIntxWeightAtenTensor(AffineQuantizedTensor):
Why do we need a subclass of AffineQuantizedTensor?  What is wrong with using the existing to_affine_quantized_intx method?

2025-01-20 12:02 UTC, ng-05 commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +class PackedLinearInt8DynamicActivationIntxWeightAtenTensor(AffineQuantizedTensor):
This is suggested by one of the Pytorch reviewer: https://github.com/pytorch/ao/pull/1447#discussion_r1919517652
from_plain method needs specialization to accomodate bias. AffineQuantizedTensor provides a generic flow where specialization was possible but Jerry suggested to seprate the flow.

2025-01-20 12:03 UTC, ng-05 commented
> Overall I think it's close. Can you be sure to run `torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py` to make sure the tests pass. It is not currently enabled in CI.
> 
> You should also add some test cases for your new target to that file to check accuracy/exportability.
> 
> I'll be out for the week of January 20, but @digantdesai should be able to help with review during that time.

I can not run this test as the op build is broken for aarch64 linux.

2025-01-20 12:04 UTC, ng-05 commented on torchao/experimental/quant_api.py
> +                        scale_dtype = torch.bfloat16 # KleidiAI kernel requires bfloat16 scale_dtype
Yes , thats the implementation detail for groupwise kernel. Channelwise( PerRow ) kernel can accept float32 scales

2025-01-20 12:09 UTC, ng-05 commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
>      has_weight_zeros: Optional[bool]
We can detect bias propagation  from target=="aten" or from has_bias. I dont think we need both if we are making target part of PackedLinearInt8DynamicActivationIntxWeightLayout().
Where do you want to use ```has_bias``` and what is the usecase?

2025-01-20 13:10 UTC, ng-05 commented on torchao/experimental/quant_api.py
> +    elif not isinstance(layout, PlainLayout):
Refactored this

2025-01-20 13:11 UTC, ng-05 commented on torchao/experimental/quant_api.py
> +    if target == "aten":
I have refactored the checks logic. It is now better encapsulated

2025-01-21 11:41 UTC, ng-05 commented
@digantdesai @jerryzh168 can I please get your latest review on this. I have addressed all the review comments from @metascroy

2025-01-23 03:57 UTC, digantdesai commented
> I can not run this test as the op build is broken for aarch64 linux.

Can you remind me of this issue? how can we resolve this?

2025-01-23 03:57 UTC, digantdesai reviewed
I think with extended AQT it is close. Left some comments.

2025-01-23 03:57 UTC, digantdesai commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +class PackedLinearInt8DynamicActivationIntxWeightAtenTensor(AffineQuantizedTensor):
Curious, (1) why adding bias as optional `to_affine_quantized_intx` isn't an option? or alternatively, (2) for native kernels we will add bias support sooner rather than later, so should we use this for both native and aten?

2025-01-23 10:44 UTC, ng-05 commented
> > I can not run this test as the op build is broken for aarch64 linux.
> 
> Can you remind me of this issue? how can we resolve this?

We need to check for ```aarch64``` in cmake processor along with arm64. Even after that I am seeing few build issues. I did not have a deeper look at them.

2025-01-23 10:47 UTC, ng-05 commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +        assert layout.target in {Target.NATIVE, Target.ATEN}, f"Unexpected target: {layout.target}"
if bias is none and target layout.target != ATEN then execution will never reach this point. It will be executed via the "native" target which has bias assert.  Please check here: https://github.com/pytorch/ao/pull/1447/files#diff-3e4ffa192fe9921999dd6a798fc3fa620377896ef9ba65245b1e5ab8c0d7d344R593

2025-01-23 10:51 UTC, ng-05 commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +    ATEN = auto()
I decided to stick to aten so that more ops from aten can be added in future if needed. This enables this layout to work with torchao ops and aten ops.
```dyn_quant_matmul_4bit``` is not supposed to be KleidiAI specific only

2025-01-23 11:17 UTC, ng-05 commented
@digantdesai 
for this comment :
Curious, (1) why adding bias as optional to_affine_quantized_intx isn't an option? or alternatively, (2) for native kernels we will add bias support sooner rather than later, so should we use this for both native and aten?

Please check 
https://github.com/pytorch/ao/pull/1447#discussion_r1922297356 and https://github.com/pytorch/ao/pull/1447#discussion_r1919517652

This change was suggested by @jerryzh168

2025-01-27 20:12 UTC, digantdesai commented
> @digantdesai for this comment : Curious, (1) why adding bias as optional to_affine_quantized_intx isn't an option? or alternatively, (2) for native kernels we will add bias support sooner rather than later, so should we use this for both native and aten?
> 
> Please check [#1447 (comment)](https://github.com/pytorch/ao/pull/1447#discussion_r1922297356) and [#1447 (comment)](https://github.com/pytorch/ao/pull/1447#discussion_r1919517652)
> 
> This change was suggested by @jerryzh168

What about (2)?

2025-01-27 20:14 UTC, digantdesai commented
I am ok with merging this for now, and since we will have to figure out details between native and aten for intx, we can resolve this later.

Stamping to unblock you.

2025-01-28 10:50 UTC, ng-05 commented
@pytorchbot merge

2025-01-28 12:15 UTC, ng-05 commented
@pytorchbot merge

2025-01-28 19:20 UTC, metascroy commented on torchao/experimental/quant_api.py
> +                has_weight_zeros != True or \
I think different people have used the term symmetric differently.  Some people use it to mean the zero point is 0, but other people use it to mean the range is symmetric (e.g., -7 to +7).

It looks like you are using an asymmetric quant range of [-8, +7] with zeropoint being 0.  The quantizer should do this if you specify has_weight_zero=False (which does scale-only quantization and is tied to zero_point_domain being NONE) and weight_mappinMappingType.ASYMMETRIC (indicating the asymmetric range).

I introduced has_weight_zeros earlier because @kimishpatel did not like symmetric being synonymous with the zero point being 0.

2025-01-28 21:45 UTC, metascroy commented
> > Overall I think it's close. Can you be sure to run `torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py` to make sure the tests pass. It is not currently enabled in CI.
> > You should also add some test cases for your new target to that file to check accuracy/exportability.
> > I'll be out for the week of January 20, but @digantdesai should be able to help with review during that time.
> 
> I can not run this test as the op build is broken for aarch64 linux.

I added CI to run torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py so you don't have to do it locally (.github/workflows/torchao_experimental_test.yml).  Just make sure the "Run TorchAO Experimental Tests" job finishes successfully before merging.

I don't see any tests for your new quantization code added.  For now, can you add a new test file (e.g., torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout_target_aten.py) that tests your quantizer/kernel code.  Later I can merge the existing test_packed_linear_int8_dynamic_activation_intx_weight_layout.py and the tests for aten target in the new file you create into one test. 

You can your test to CI by adding a line here: https://github.com/pytorch/ao/blob/main/.github/workflows/torchao_experimental_test.yml#L42

2025-01-28 22:16 UTC, digantdesai commented
Good point about tests, @ng-05 can we please add them? Also in the CI now?

2025-01-30 16:29 UTC, ng-05 commented
> Good point about tests, @ng-05 can we please add them? Also in the CI now?

Done.

2025-01-30 16:29 UTC, ng-05 commented
> > > Overall I think it's close. Can you be sure to run `torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py` to make sure the tests pass. It is not currently enabled in CI.
> > > You should also add some test cases for your new target to that file to check accuracy/exportability.
> > > I'll be out for the week of January 20, but @digantdesai should be able to help with review during that time.
> > 
> > 
> > I can not run this test as the op build is broken for aarch64 linux.
> 
> I added CI to run torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout.py so you don't have to do it locally (.github/workflows/torchao_experimental_test.yml). Just make sure the "Run TorchAO Experimental Tests" job finishes successfully before merging.
> 
> I don't see any tests for your new quantization code added. For now, can you add a new test file (e.g., torchao/experimental/tests/test_packed_linear_int8_dynamic_activation_intx_weight_layout_target_aten.py) that tests your quantizer/kernel code. Later I can merge the existing test_packed_linear_int8_dynamic_activation_intx_weight_layout.py and the tests for aten target in the new file you create into one test.
> 
> You can your test to CI by adding a line here: https://github.com/pytorch/ao/blob/main/.github/workflows/torchao_experimental_test.yml#L42

Thank you very much. I have done the requested changes around tests. Please review

2025-01-30 16:55 UTC, digantdesai commented on torchao/experimental/packed_linear_int8_dynamic_activation_intx_weight_layout.py
> +    ATEN = auto()
But the aten implementation and the packing routine it selects is Kleidi specific.

2025-01-30 16:56 UTC, merged