[8da4w] Add support to skip quantizing some layers
pytorch/ao pull request #239
Opened 2024-05-14 20:23 UTC by andrewor14

Summary: Certain layers in llama3 are more sensitive to quantization than others. In general, we need a mechanism to skip quantizing certain parts of the model. This commit adds such a mechanism by allowing users to pass in a function that filters out layers to be skipped during module swap.

Test Plan:
python test/quantization/test_quant_api.py -k test_8da4w_quantizer_skip_quantize_filter python test/quantization/test_qat.py -k test_qat_8da4w_quantizer_skip_quantize_filter

Reviewers: jerryzh168, cpuhrsch

Subscribers: jerryzh168, cpuhrsch, supriyar

2024-05-14 22:07 UTC, cpuhrsch requested changes
Is it possible to apply GPTQ layer by layer and just skip it from the outside instead of replicating pattern matching logic within the constructor? Seems more flexible to keep GPTQ as is and teach it how to operate on sub-model level. Happy to chat further.

2024-05-15 01:35 UTC, andrewor14 commented
> Is it possible to apply GPTQ layer by layer and just skip it from the outside instead of replicating pattern matching logic within the constructor? Seems more flexible to keep GPTQ as is and teach it how to operate on sub-model level. Happy to chat further.

Sure it's possible, but I think it's less user friendly. For example, let's say you want to skip quantizing all the `v_proj` layers in llama3. Right now the only way is to manually specify all the other layers that need quantizing, which is verbose and potentially error prone. I feel it's more natural to express this as an exclusion and it will make our APIs easier to use. What do you think?

2024-05-15 19:31 UTC, cpuhrsch commented
@andrewor14 , is it possible to do

```
for name, mod in model.named_modules():
    if "v_proj" in name:
        continue
    <apply GPTQ>
```

2024-05-15 20:42 UTC, andrewor14 commented
> @andrewor14 , is it possible to do
> 
> ```
> for name, mod in model.named_modules():
>     if "v_proj" in name:
>         continue
>     <apply GPTQ to mod>
> ```

Yeah, that looks reasonable. I'll close this PR

2024-05-15 20:42 UTC, closed without merging