Bitpackingv2
pytorch/ao pull request #307
Opened 2024-06-03 17:33 UTC by vayuda

Improved code structure of the pack/unpack functions
Now supports trinary for bitnet applications
Now supports packing along any dimension for any size tensors

2024-06-03 18:23 UTC, msaroufim requested changes
Left some feedback here and in cuda mode, my worry is this code will be slow so will need some benchmarks and it's a big loss to lose torch.compile support

2024-06-03 18:23 UTC, msaroufim commented on test/prototype/test_bitpacking.py
> -    pack_compiled = torch.compile(pack, fullgraph=True)
I noticed you're not using compile anymore? I also worry that functions that include `.shape` in them will cause a cuda sync and be very slow

2024-06-03 18:23 UTC, msaroufim commented on torchao/prototype/common/bitpacking.py
> +def dtype_to_bits(dtype):
nit: can you make this a dictionary instead?

2024-06-03 18:23 UTC, msaroufim commented on test/prototype/test_bitpacking.py
> +    for dtype in {torch.uint2, torch.uint3, torch.uint4, torch.uint5, torch.uint6, torch.uint7}:
favor pytest parametrize that way it'll be easier to identify the failing test in CI

2024-06-03 20:53 UTC, msaroufim commented on test/prototype/test_bitpacking.py
> +    unpack_compile = torch.compile(unpack, fullgraph=True)
you need to run the function to test it since compile is a JIT compiler

2024-06-03 21:26 UTC, gau-nernst commented on torchao/prototype/common/bitpacking.py
> +    element_dtype: the dtype of the elements to pack
I think keeping `element_size` (or maybe change to `element_bit_width`) is better. Then `dtype_to_bits()` doesn't need to support uint2-7 (so you can use `torch.finfo()` and `torch.iinfo()`)

2024-06-10 15:49 UTC, msaroufim commented on torchao/prototype/common/bitpacking.py
> +if __name__ == '__main__':
Not a huge fan of having usage instructions in a python file. Ideally this should be a test instead or some usage example in a README in the `common/` folder

2024-06-10 15:56 UTC, msaroufim commented on torchao/prototype/common/bitpacking.py
> +    if element_type == "trinary":
can you add a quick comment here?

2024-06-10 15:56 UTC, msaroufim commented on torchao/prototype/common/bitpacking.py
> +    print(packed.shape)
turn these into logging statements

2024-06-10 15:58 UTC, msaroufim requested changes
few minor pieces of feedback: comments would be nice too

2024-06-10 18:40 UTC, msaroufim approved these changes

2024-06-10 18:40 UTC, merged